#versao do script
version: '3.9'

# criando um serviço
services:
  # criando o primeiro serviço: banco de dados
  db:
    restart: always
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=person_db
    ports:
      - '5433:5432'
    networks:
      - dev-network

  #Criando o serviço da nossa aplicação
  curso-api:
      restart: always
      build: /home/mateus/Personal/CursoAPI
      working_dir: /home/mateus/Personal/CursoAPI
      environment:
        TZ: America/Sao_Paulo
        SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/person_db?useTimezone=true&serverTimezone=UTC
        SPRING.DATASOURCE.USERNAME: postgres
        SPRING.DATASOURCE.PASSWORD: postgres
      ports:
        - '8888:8888'
      depends_on:
        - db
      volumes:
        - /home/mateus/Personal/CursoAPI/wait-for-db.sh:/usr/local/bin/wait-for-db.sh
      networks:
        - dev-network
networks:
  dev-network:
    driver: bridge