cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br
file:
  upload-dir: /home/mateus/Downloads/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/person_db?useTimezone=true&serverTimezone=UTC
      username: postgres
      password: postgres
  jpa:
    hibernate: 
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  # Configurando o multpart para receber arquivos
  servlet:
    multipart:
      enabled: true #permitindo o multpart
      file-size-threshold: 2KB #tamanho em kbtes que vamos armazenar em memoria e, se, passando disso, vamos armazenar em disco
      max-file-size: 200MB #tamanho maximo de armazenamento
      max-request-size: 215MB
  flyway:
    baselineOnMigrate: true
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true